name: Deploy to NPM
on:
  push:
    branches:
      - main

env:
  NPM_ACCESS_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build Package
        run: npm run build
